language: node_js
node_js:
  - "0.12"
after_success:
  - npm install && harp compile uglify --source ./www/assets/css/main.css --output ./www/assets/css/main.css uglify --source ./www/assets/js/app.js --output ./www/assets/js/app.js && surge --project ./www --domain iammatthias.com
