language: node_js
node_js:
  - "0.12"
after_success:
  - npm install && harp compile && uglify -s ./www/assets/css/main.css -c -o ./www/assets/css/main.css && uglify -s ./www/assets/js/app.js -o ./www/assets/js/app.js && surge --project ./www --domain iammatthias.com
